### ISSUE TITLE
Moving Repository

### ISSUE THREAD

**Issue by mcrute** [mcrute/alpine-ec2-ami#120]
This is a public notice that this repository will be moving around the end of May 2021. The repository will be imported with all of its history to [Alpine GitLab](https://gitlab.alpinelinux.org). The new home of the repository will be:

```
https://gitlab.alpinelinux.org/alpine/cloud/alpine-ec2-ami
```

Please update your git remotes to one of these:

```
git@gitlab.alpinelinux.org:alpine/cloud/alpine-ec2-ami.git
https://gitlab.alpinelinux.org/alpine/cloud/alpine-ec2-ami.git
```

I will comment on this issue one day before the move begins and close it before I being the migration. After that time this GitHub repository will redirect everyone to the GitLab repository.

**Comment by tomalok** [comment]
@mcrute - I'm not sure this has happened yet or not.

Either way, I've forked this repo over to https://gitlab.alpinelinux.org/tomalok/alpine-cloud-images  to move forward with
* supporting more cloud providers - and a better way of defining image "dimensions" and generating profile build matrices
* moving cloud-specific and bootstrap-specific stuff over to https://github.com/mcrute/alpine-ec2-ami (which was also forked over to https://gitlab.alpinelinux.org/tomalok/tiny-cloud-bootstrap) so that `cloud-init` image flavors can be built without tripping over similar functionality we've put in here (mdev scripts, networking, EBS aliasing, etc.)
* defining Packer configs with HCL2, and taking advantage of its features
* if possible, building the images **locally** with `qemu`, instead of having to spin up additional build instances in the cloud
* CI/CD for auto-build/test/release of new images when new Alpine releases land
* retain and enhance the ability for people to "roll their own" using this same toolset

Forthcoming changes to both tiny-cloud-bootstrap and alpine-cloud-images could be extensive, I feel better having a safer place to play...

**Comment by mcrute** [comment]
@tomalok sorry, I've once again had very limited time to focus on this project. I can not access your fork, can you give me at least read access?

The migration has been completed and the new official URL is https://gitlab.alpinelinux.org/alpine/cloud/alpine-ec2-ami/.

We need Alpine admins to make this public but you should have full maintainer access as a member of the cloud team, I anticipate it being made public on Alpine GitLab very soon. I will be purging this repo on GitHub and marking it as moved this weekend. Please migrate future changes to the official repository.
