### ISSUE TITLE
Update set of publicly available AMIs

### ISSUE THREAD

**Issue by tomalok** [mcrute/alpine-ec2-ami#19]
We should be able to retire the 3.7 AMIs in favor of 3.8-r1 (aka 3.8.1).

@mcrute - I could host them publicly from my account if you'd rather not.

**Comment by mcrute** [comment]
I'll do a manual build of the 3.8 AMI and remove the 3.7 ones either today or early this next week. Once that's done I'll resolve this issue.

The long term plan for this repo has been to validate the AMI concept and get everything in stable working order then to contribute the whole thing upstream. To that end I'm planning to create an entirely new AWS account and host the AMIs from there so that it's easier to send upstream. I've forked that off into #21. I'd also like to get CI setup so we can roll new images easily, I've forked that task off into #22.

Once I get this setup I'll give you access so there's more than just one person who can do releases. Would you mind dropping me an email to the address on my GitHub profile and we'll work that out off-issue.

**Comment by tomalok** [comment]
PR #38 on deck for a set of 3.9.0 AMIs.

**Comment by tomalok** [comment]
Updated!
