### ISSUE TITLE
docker daemon won't run

### ISSUE THREAD

**Issue by dominicholt** [mcrute/alpine-ec2-ami#3]
I can successfully install docker on the ec2 instance through APK, but when I try to run "docker ps", I always get this error/; 

Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

**Comment by mcrute** [comment]
Have you verified that docker is running? Have you tried running the docker command line as root? Because it's pretty easy to escalate privileges if you have access to the docker daemon they tend to be fairly conservative with their socket permissions. Check the permissions on `/var/run/docker.sock`.

Hope that helps. If this ends up being an problem with the AMI and not docker please re-open this issue.

**Comment by oliwer** [comment]
I reproduced this bug with alpine-ami-3.9.3. I used the following user-data:

    #!/bin/sh
    apk update
    apk add docker
    service docker start

And here is what i see in /var/log/messages

    daemon.err /etc/init.d/docker[2526]: ERROR: cannot start docker as cgroups would not start

Yet, when I login to the VM and start docker myself it works fine. Could this be because tiny-ec2-bootstrap runs too early? Maybe `sysfs` is not ready yet? I'm not sure how to debug this.

**Comment by tomalok** [comment]
Took a look at my `user-data` script that starts up docker (and does some other misc things), and here's what I'm doing...
```
rc-update add cgroups boot
rc-update add docker default
service cgroups start
service docker start
```
Some time after I wrote that script, I've also taken maintainership of Alpine's `docker` packages, but apparently I forgot about this.  I'll add a `cgroups` dependency for the docker init script, should be in the next Alpine version (3.10)...  In the meantime, be sure to start `cgroups` first... :)

**Comment by tomalok** [comment]
Turns out the `need cgroups` dependency is already there.

I instantiated a new image, logged in, and did `apk -U add docker && /etc/init.d/docker start` (as root) and that indeed works.  Running with a similar `user-data` doesn't -- this is probably a bug and/or caveat with [tiny-ec2-bootstrap](https://github.com/mcrute/tiny-ec2-bootstrap).

As you can see from my solution above, I had run into this, too...  (though I probably didn't need to explicitly add `cgroups` to the boot run level.)

It is possible with `alpine-ec2-ami` to build your own custom AMIs -- you could build one that already has `docker` at default runlevel, it should come up just fine.  Or if you need to do some fiddling before starting it the first time, don't add it to default in your image, and have a `user-data` script do something like this ...
```
#!/bin/sh

# (other stuff, setup, config here)
 
rc-update add docker default
touch /var/lib/cloud/.bootstrap-complete
/sbin/reboot
```
...this will set stuff up, the `docker` service to the default runlevel, ensure that tiny-ec2-bootstrap won't run a second time, and then reboot.

**Comment by oliwer** [comment]
Thanks a lot @tomalok. For now, explicitly starting cgroups before docker will do :)

I bet it's `keyword -docker` in /etc/init.d/cgroups that is blocking us.
