### ISSUE TITLE
How do delete generated AMIS and limit region?

### ISSUE THREAD

**Issue by munntjlx** [mcrute/alpine-ec2-ami#57]
Great script, but I don't see how I can ONLY create 1 image in 1 region. How do I delete 'accidental' images in EVERY region?

**Comment by tomalok** [comment]
Hi @munntjlx 

I'm assuming you've copied `profiles/alpine.conf` to some other file in `profiles/`?

You will want to change...
```
  ami_regions {
    ALL = true
  }
```
...to...
```
  ami_regions = null
  ami_regions = {}
```

When `ami_regions` is unset like this, the built AMI will be in the region specified by the `build_region` value.  Without first setting it to `null`, the previous contents of `ami_regions` get merged with the empty hash, yielding no change.  I believe this behavior is noted in `profiles/README.md` -- if it's unclear, please let me know and/or suggest alternate wording.

And because the base core profile already sets `ami_regions = {}` as the default, you could also simply just remove `ami_regions` altogether from your profile config (again, assuming you've copied `alpine.conf`).

Also, if you don't intend your AMI to be public, remember to do the same for `ami_access`... :)

With regards to deleting accidental images in EVERY region, that's a little tricker.  If the AMIs are `edge` builds (with timestamps) simply wait 24h  and then...
```
make prune PROFILE=<your-profile> LEVEL=version  BUILD=<edge-build-target>
```
...note that this will also remove the AMI from the region you want to keep.

If your AMI is not edge, and there hasn't been a new version, release, or revision, `prune` probably won't help you out, and you'll probably have to either manually remove them via console or CLI -- note that `builds/<your-profile>.yaml` will at least contain a list of the AMI ARNs per region.
